# roles/webserver/tasks/main.yml
---
- name: 1. Install Apache
  apt: name=apache2 state=present

- name: 2. Install PHP 7.0
  apt: name=php7.0 state=present

- name: 3. Install Apache PHP module
  apt: name=libapache2-mod-php7.0 state=present

- name: 4. Install PHP 7.0 CLI
  apt: name=php7.0-cli state=present

- name: 5. Install PHP 7.0 Common API
  apt: name=php7.0-common state=present

- name: 6. Install PHP 7.0 MBString library
  apt: name=php7.0-mbstring state=present

- name: 7. Install PHP 7.0 GD library
  apt: name=php7.0-gd state=present

- name: 8. Install PHP 7.0 INTL library
  apt: name=php7.0-intl state=present

- name: 9. Install PHP 7.0 XML library
  apt: name=php7.0-xml state=present

- name: 10. Install PHP 7.0 MySQL library
  apt: name=php7.0-mysql state=present

- name: 11. Install PHP 7.0 MCrypt library
  apt: name=php7.0-mcrypt state=present

- name: 12. Install PHP 7.0 Zip library
  apt: name=php7.0-zip

- name: 13. Start Apache
  service: name=apache2 state=started enabled=yes

- name: 14. Install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: 15. Remove index.html file
  file: path=/var/www/html/index.html state=absent

